//
//  SNRender.swift
//  SolidNative
//
//  Created by LZY on 2024/5/3.
//

import Foundation
import JavaScriptCore
import SwiftUI
/**
 Acts as renderer.
 */
let vm = ViewManager()
class SNRender: SolidNativeModule {
    class override var name: String {
        "SNRender"
    }
    
    private let viewManager = vm//ViewManager()

    required init() {
        let _ = viewManager.addViewToRegistry(view: SolidNativeCore.shared.rootElement)
        
        // TODO: This needs to be dynamic! Since other code needs to be able to access it.
        // TODO: OR, maybe just have some shared module. Or this could just be autogenerated.
        viewManager.registerElement(SNTextView.self);
        viewManager.registerElement(SNView.self);
        viewManager.registerElement(SNButtonView.self);
        viewManager.registerElement(SNScrollView.self);
        viewManager.registerElement(SNToggle.self);
        viewManager.registerElement(SNAsyncImage.self);
        viewManager.registerElement(SNVStack.self);
        viewManager.registerElement(SNHStack.self);
        viewManager.registerElement(SNZStack.self);
        viewManager.registerElement(SNLazyVStack.self);
        viewManager.registerElement(SNLazyHStack.self);
        viewManager.registerElement(SNSpacer.self);
        viewManager.registerElement(SNSlider.self);
        viewManager.registerElement(SNTextField.self);
        viewManager.registerElement(SNSecureField.self);
        viewManager.registerElement(SNLazyVGrid.self);
        viewManager.registerElement(SNRectangle.self);
        viewManager.registerElement(SNWebImage.self);
        viewManager.registerElement(SNList.self)
        viewManager.registerElement(SNLabel.self)
        viewManager.registerElement(SNTabView.self)
        viewManager.registerElement(SNNavigationStack.self)
        viewManager.registerElement(SNNavigationLink.self)
        
        print("[SNRender] init")
    }
    
    deinit {
        print("[SNRender] deinit")
    }
    
    override func getJSValueRepresentation() -> JSValue {
        let builder = JSValueBuilder()
        
//        builder.addSyncFunction("_pushNewPageAndGetId") {
//            let nv = SNView()
//            let id = self.viewManager.addViewToRegistry(view: nv)
//            SolidNativeCore.shared.navigationStack.append(nv)
//            Route.shared.routes.append(id)
//            return id
//        }
        
        builder.addSyncFunction("_createNewPage") {
            let nv = SNView()
            
            let id = self.viewManager.addViewToRegistry(view: nv)
            return id
        }

        builder.addSyncFunction("_pushNewPage") { (_ id: String) in
            guard let nv = self.viewManager.getViewById(id) as? SNView else { return }
            
            SolidNativeCore.shared.navigationStack.append(nv)
            Route.shared.routes.append(id)
        }
        
        builder.addSyncFunction("_createViewForControl") {
            let nv = SNView()
            let id = self.viewManager.addViewToRegistry(view: nv)
            return id
        }
        
        builder.addSyncFunction("getRootView") {
            return SolidNativeCore.shared.rootElement.id.uuidString
        }
        
        builder.addSyncFunction("getFirstChild") { (_ id: String) in
            let view = self.viewManager.getViewById(id)
            return view.firstChild?.id.uuidString
        }
        
        builder.addSyncFunction("getParent") { (_ id: String) in
            let view = self.viewManager.getViewById(id)
            return view.parentElement?.id.uuidString
        }
        
        builder.addSyncFunction("setProp") { (_ id: JSValue, name: JSValue, value: JSValue) in
            let view = self.viewManager.getViewById(id.toString()!)
            if value.isNull || value.isUndefined {
                view.setProp(name.toString()!, nil)
            } else {
                view.setProp(name.toString()!, value)
            }
        }
        
        builder.addSyncFunction("isTextElement") { (_ id: String) in
            let view = self.viewManager.getViewById(id)
            return view.isTextElement
        }
        
        builder.addSyncFunction("removeChild") { (_ id: String, childId: String) in
            let view = self.viewManager.getViewById(id)
            let viewChild = self.viewManager.getViewById(childId)
            view.removeChild(viewChild)
            self.viewManager.removeViewById(childId)
            
            print("parent: \(view.getName()), child: \(viewChild.getName())")
        }
        
        builder.addSyncFunction("insertBefore") { (_ id: JSValue, elementId: JSValue, anchorId: JSValue) in
            let view = self.viewManager.getViewById(id.toString()!)
            let element = self.viewManager.getViewById(elementId.toString()!)
            
            if anchorId.isString {
                let anchor = self.viewManager.getViewById(anchorId.toString()!)
                return view.insertBefore(element, anchor)
            }
            
            return view.insertBefore(element, nil);
        }
        
        builder.addSyncFunction("next") { (_ id: String) in
            let view = self.viewManager.getViewById(id)
            return view.next?.id.uuidString
        }
        
        builder.addSyncFunction("prev") { (_ id: String) in
            let view = self.viewManager.getViewById(id)
            return view.prev?.id.uuidString
        }
        
        builder.addSyncFunction("createNodeByName") { (_ name: String) in
            let viewId = self.viewManager.createViewByName(name);
            return viewId
        }
        
        builder.addSyncFunction("_withAnimation") { (_ fn: JSValue)  in
            _ = withAnimation {
                fn.call(withArguments:[])
            }
        }
        
        return builder.value
    }
}


// Need some way to build function.
class ViewManager {
    private var viewRegistry: [String : SolidNativeView.Type] = [:]
    var createdViewRegistry: [String: SolidNativeView] = [:]
    
    fileprivate func addViewToRegistry(view: SolidNativeView) -> String {
        let id = view.id.uuidString
        createdViewRegistry[id] = view
        return id
    }

    // Only thing it needs is the View type, the View Name, whether or not it a text view
    func registerElement(_ viewType: SolidNativeView.Type) {
        viewRegistry[viewType.name] = viewType.self
    }
    /**
     @returns view id
     */
    func createViewByName(_ name: String) -> String {
        if let viewType = viewRegistry[name] {
            let newView = viewType.init()
            return addViewToRegistry(view: newView)
        }
        assertionFailure("\(name) is not in element registry!")
        return ""
    }

    func getViewById(_ id: String) -> SolidNativeView {
        if let view = createdViewRegistry[id] {
            return view
        }
        assertionFailure("view with id \(id) is not in element registry!")
        return SolidNativeView()
    }
    
    func removeViewById(_ id: String) {
        let node = createdViewRegistry.removeValue(forKey: id)
        deactivateAllChildren(root: node)
    }
    
    // todo: 迁移到统一管理的地方
    // todo: swipeactions -> content
//    let propsToDel: [String] = ["overlay", "background", "placeholder"]

    private func deactivateAllChildren(root: SolidNativeView?) {
        guard let root = root else { return }

        createdViewRegistry.removeValue(forKey: root.id.uuidString)
        let v = root
        
//        print("[\(tag)] id: \(v.id.uuidString), name: \(v.getName())")

//        for prop in propsToDel {
//            if let jsValue = v.props.values[prop], jsValue?.isObject == true, let id = jsValue?.forProperty("id").toString() {
//                deactivateAllChildren(root: createdViewRegistry[id], tag: tag)
//            }
//        }
        
        if let nv = v as? SNTabView {
            nv.tabIds.forEach {
                print("tab id: \($0)")
                SolidNativeCore.shared.jsContext.evaluateScript("cleanPage(\"\($0)\")")
                if let c = createdViewRegistry[$0] {
                    deactivateAllChildren(root: c)
                }
            }
        }

        // 递归遍历所有子节点
        for child in root.children {
            deactivateAllChildren(root: child)
        }
        
        // 非直接子节点（属性中的）
        for child in root.indirectChildren {
            deactivateAllChildren(root: child)
        }
        
        // 如果有 next 节点，继续设置
        if let nextNode = root.next {
            deactivateAllChildren(root: nextNode)
        }
    }
    
    func removePageById(_ id: String) {
        if let v = self.createdViewRegistry[id] {
            self.deactivateAllChildren(root: v)
        }
    }
    
    func removePageByRoot(_ root: SolidNativeView) {
        self.deactivateAllChildren(root: root)
    }
    
    func clearAll() {
        viewRegistry = [:]
        
        createdViewRegistry.forEach { key, val in
            val.next = nil
            val.prev = nil
            val.parentElement = nil
            val.firstChild = nil
            val.children.removeAll()
        }
        createdViewRegistry = [:]
    }
    
    deinit {
        print("[ViewManager] deinit")
    }
}
